# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
email: zerafachris@gmail.com 
description: >- # this means to ignore newlines until "baseurl:"
  "Portfolio website for "Dr. Christopher Zerafa, PhD".
# twitter_username: username
github_username: zerafachris
minimal_mistakes_skin: air # "default", "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"
search: true
locale: "en"
title: "Dr. Christopher Zerafa, PhD"
# subtitle: "Portfolio | About"
name: "Dr. Christopher Zerafa, PhD"
url: "https://zerafachris.github.io"
repository : "zerafachris/bio"
logo: "/assets/images/CZ-logo.png" # https://pmav.eu/stuff/pictar/
# Favicon generator:
# https://favicon.io/favicon-converter/
masthead_title: "Dr. Christopher Zerafa, PhD"


# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: Europe/Malta # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
# RSS feed
atom_feed:
  hide: true

# The default search uses Lunr to build a search index of all post and your documents in collections. 
# This method is 100% compatible with sites hosted on GitHub Pages.
# To have it index all pages, update lunr in _config.yml like so:
lunr:
  search_within_pages: true

# SEO, social sharing, and analytics settings 
# https://mmistakes.github.io/minimal-mistakes/docs/configuration/#seo-social-sharing-and-analytics-settings
## Google
google_site_verification: "JtMDjGGvDVUMyySqt71k48ftpim0Y9WZSUY2_qFZROY"

analytics:
  provider: "google-gtag"
  google:
    tracking_id: "G-46G8R7CZ33"
    anonymize_ip: false # default


include:
  - _pages
  - _posts

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

# Site Author
# https://mmistakes.github.io/minimal-mistakes/docs/configuration/#site-author
author:
  name   : "Dr. Christopher Zerafa, PhD"
  # avatar : "/assets/images/bio-photo.jpg"
  bio    : "Data leader, driving transformative change at the intersection of AI and technology."
  # location: "Malta"
  # email: "zerafachris@gmail.com"
  links:
    - label: "CV"
      icon: "fas fa-fw fa-university"
      url: "https://www.linkedin.com/in/christopherzerafa/"
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
      url: "mailto:zerafachris@gmail.com"
    - label: "Website"
      icon: "fas fa-fw fa-link"
      url: "https://zerafachris.github.io/bio/"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/zerafachris"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/christopherzerafa/"
    

footer:
  links:
    - label: "CV"
      icon: "fas fa-fw fa-university"
      url: "https://www.linkedin.com/in/christopherzerafa/"
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
      url: "mailto:zerafachris@gmail.com"
    - label: "Website"
      icon: "fas fa-fw fa-link"
      url: "https://zerafachris.github.io/bio/"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/zerafachris"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/christopherzerafa/"
    - label: 'Tags'
      icon: "fas fa-fw fa-tags"
      url: "/bio/tags/"
    - label: 'Posts'
      icon: "fas fa-fw fa-file"
      url: "/bio/posts/"
    

defaults:
  # _pages
  - scope:
      path: ""
      type: posts
    values:
      show_date: true
      date_format: "%Y-%m-%d"
      read_time: true
      comments: true
      layout: single
      author_profile: true
      share: true
      related: true
  # _foo
  - scope:
      path: ""
      type: foo
    values:
      layout: single

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

# HTML Compression
# https://mmistakes.github.io/minimal-mistakes/docs/configuration/#html-compression
compress_html:
  clippings: all
  ignore:
    envs: development