name: Convert Markdown to HTML and Post to LinkedIn

on:
  push:
    paths:
      - "_posts/*.md"  # Trigger when Markdown files in the '_posts' folder are updated
  workflow_dispatch:

jobs:
  convert_and_post:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Convert Markdown to HTML
      - name: Convert Markdown to HTML
        uses: jd-solanki/gh-action-md-to-html@v1.3.0
        with:
          files: '[["_posts/example.md", "output/example.html"]]'  # Replace with your file paths

      # Step 3: Post HTML to LinkedIn
      - name: Post Article to LinkedIn
        uses: p4p1/linkedin-marketing-workflow@main
        with:
          LINKEDIN_SECRET: ${{ secrets.LINKEDIN_SECRET }}  # Your LinkedIn API token stored in secrets
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}         # GitHub token for authentication
          FILE_PATH: output/example.html                     # Path to the converted HTML file
